# Generated by Django 3.2.7 on 2021-09-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=10000)),
                ('tags', models.CharField(default='General', max_length=200)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
