# Generated by Django 3.2.7 on 2021-09-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inotebook_backend', '0002_notes_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='data',
            new_name='date',
        ),
    ]
